export const mockClothItems = [
  // 상의
  {
    id: 6001,
    name: "fashion_top_1.png",
    description: "기본 반팔 티셔츠",
    type: "TOP",
    price: 120,
    theme: ["데일리", "심플", "여름"],
    created_at: "2025-08-01",
  },
  {
    id: 6002,
    name: "fashion_top_2.png",
    description: "스트라이프 셔츠",
    type: "TOP",
    price: 180,
    theme: ["댄디", "봄", "데일리"],
    created_at: "2025-08-02",
  },
  // 하의
  {
    id: 7001,
    name: "fashion_bottom_1.png",
    description: "편안한 청바지",
    type: "BOTTOM",
    price: 220,
    theme: ["데일리", "캐주얼"],
    created_at: "2025-08-03",
  },
  {
    id: 7002,
    name: "fashion_bottom_2.png",
    description: "검정 슬랙스",
    type: "BOTTOM",
    price: 190,
    theme: ["심플", "댄디"],
    created_at: "2025-08-04",
  },
  // 세트
  {
    id: 8001,
    name: "fashion_set_1.png",
    description: "하늘색 원피스 세트",
    type: "SET",
    price: 450,
    theme: ["러블리", "여름", "포인트"],
    created_at: "2025-08-05",
  },
  // 신발
  {
    id: 9001,
    name: "fashion_shoes_1.png",
    description: "기본 스니커즈",
    type: "SHOES",
    price: 150,
    theme: ["데일리", "심플"],
    created_at: "2025-08-06",
  },
  // 액세서리
  {
    id: 10001,
    name: "fashion_acc_ears_1.png",
    description: "베이지 버킷햇",
    type: "EARS",
    price: 80,
    theme: ["여름", "캐주얼"],
    created_at: "2025-08-07",
  },
  {
    id: 10002,
    name: "fashion_acc_head_1.png",
    description: "동그란 안경",
    type: "HEAD",
    price: 60,
    theme: ["심플", "포인트"],
    created_at: "2025-08-07",
  },
  {
    id: 10003,
    name: "fashion_acc_neck_1.png",
    description: "진주 목걸이",
    type: "NECK",
    price: 120,
    theme: ["러블리", "봄"],
    created_at: "2025-08-07",
  },
  {
    id: 10004,
    name: "fashion_acc_leftWrist_1.png",
    description: "실버 체인 팔찌",
    type: "LEFTWRIST",
    price: 95,
    theme: ["심플", "데일리", "포인트"],
    created_at: "2025-08-08",
  },
  {
    id: 10006,
    name: "fashion_acc_leftHand_1.png",
    description: "심플한 은반지",
    type: "LEFTHAND",
    price: 70,
    theme: ["심플", "데일리"],
    created_at: "2025-08-09",
  },
  {
    id: 10007,
    name: "fashion_acc_leftHand_2.png",
    description: "골드 너클 링",
    type: "LEFTHAND",
    price: 85,
    theme: ["스트릿", "포인트"],
    created_at: "2025-08-09",
  },
  {
    id: 10008,
    name: "fashion_acc_eyes_1.png",
    description: "블랙 선글라스",
    type: "EYES",
    price: 130,
    theme: ["여름", "시크", "포인트"],
    created_at: "2025-08-10",
  },
];
